BW_ROCKSDB='/group/ctbrowngrp5/sra-metagenomes/20241128-k21-s1000'

SPECIES, = glob_wildcards('{s}.cds.sig.zip')
MINS=[2,10,20,50,80,90,95]
SCALED=[1000, 5000, 10000, 100000]

wildcard_constraints:
    m="\d+",
    scaled="\d+",

rule all:
    input:
        expand('outputs.branchwater/manysearch.{s}.parquet', s=SPECIES),
        expand('outputs.branchwater.min{m}/manysearch.{s}.parquet', s=SPECIES, m=MINS),
        expand('outputs.branchwater.min{m}.scaled{scaled}/manysearch.{s}.parquet', s=SPECIES, m=MINS, scaled=SCALED),
        expand('outputs.minsig/{s}.cds.min{m}.sig.zip', s=SPECIES, m=MINS),
        expand("outputs.3216.min{m}/manysearch.3216.csv", m=MINS)

rule kmers:
    input:
        expand('outputs.minsig/{s}.cds.min90.fa', s=SPECIES),
        expand('outputs.minsig/{s}.cds.min90.dedup.fa', s=SPECIES),
        expand('outputs.minsig/{s}.cds.min90.dedup.sig.zip', s=SPECIES),

rule minsig:
    input:
        sig='{s}.cds.sig.zip',
        metags='../../../outputs.mapping/rand-metags.mf.csv',
    output:
        'outputs.minsig/{s}.cds.min{m}.sig.zip'
    shell: '''
        ../../../scripts/screen-sigs-x-metags.py {input.sig:q} {input.metags:q} -m {wildcards.m} -o {output:q} -k 21
    '''
    

rule csv_to_parquet:
    input:
        '{filename}.csv',
    output:
        touch('{filename}.parquet'),
    params:
        dirname=lambda w: os.path.dirname(w.filename)
    shell: """
        ../../../scripts/csv-to-parquet.py {input:q} -o {params.dirname:q}
    """

rule search_species:
    input:
        q="{species}.cds.sig.zip",
        db=BW_ROCKSDB,
    output:
        "outputs.branchwater/manysearch.{species}.csv",
    #conda: "env-sourmash.yml"
    threads: 1
    shell: """
        sourmash scripts manysearch -c {threads} -t 0 -k 21 -s 1000 \
            {input.q:q} {input.db:q} -o {output:q}
    """

rule search_species_min:
    input:
        q="outputs.minsig/{species}.cds.min{m}.sig.zip",
        db=BW_ROCKSDB,
    output:
        "outputs.branchwater.min{m}/manysearch.{species}.csv",
    #conda: "env-sourmash.yml"
    threads: 1
    shell: """
        sourmash scripts manysearch -c {threads} -t 0 -k 21 -s 1000 \
            {input.q:q} {input.db:q} -o {output:q}
    """

rule search_species_min_scaled:
    input:
        q="outputs.minsig/{species}.cds.min{m}.sig.zip",
        db=BW_ROCKSDB,
    output:
        "outputs.branchwater.min{m}.scaled{scaled}/manysearch.{species}.csv",
    #conda: "env-sourmash.yml"
    threads: 1
    shell: """
        sourmash scripts manysearch -c {threads} -t 0 -k 21 -s {wildcards.scaled} \
            {input.q:q} {input.db:q} -o {output:q}
    """

rule species_min_mf:
    input:
        expand("outputs.minsig/{s}.cds.min{{m}}.sig.zip", s=SPECIES)
    output:
        "output.minsig/mf.min{m}.csv"
    shell: """
        sourmash sig collect -F csv {input:q} -o {output:q} --abspath
    """
        
rule search_species_min_3216:
    input:
        q="output.minsig/mf.min{m}.csv",
        db="../../../3216.manifest.csv",
    output:
        "outputs.3216.min{m}/manysearch.3216.csv",
    #conda: "env-sourmash.yml"
    threads: 32
    shell: """
        sourmash scripts manysearch -c {threads} -t 0 -k 21 -s 1000 \
            {input.q:q} {input.db:q} -o {output:q}
    """

rule kmers_wc:
    input:
        sig='outputs.minsig/{s}.cds.min90.sig.zip',
        seqs='../{s}.cds.fa.gz',
    output:
        fa='outputs.minsig/{s}.cds.min90.fa',
    shell: """
        sourmash sig kmers --sig {input.sig:q} --sequences {input.seqs:q} \
            --save-sequences {output.fa:q} -k 21
    """
        
    
rule cdhit_wc:
    input:
        fa='outputs.minsig/{s}.cds.min90.fa',
    output:
        fa='outputs.minsig/{s}.cds.min90.dedup.fa',
    threads: 16
    shell: """
        cd-hit -c 1.0 -i {input.fa:q} -o {output:q} -T {threads} -M 5000
    """
        
    
rule sketch_dedup:
    input:
        fa='outputs.minsig/{s}.cds.min90.dedup.fa',
    output:
        fa='outputs.minsig/{s}.cds.min90.dedup.sig.zip',
    shell: """
        sourmash sketch dna -p k=21,k=31,k=51 {input.fa:q} -o {output.fa:q} \
           --name {wildcards.s:q}
    """
        
    
